title: JIT ML-101
description: Website to host content for introductory ML course offered to students at JIT.
theme: just-the-docs

url: https://rumaisaabdulhai.github.io/jit-ml

aux_links:
  Visit JIT: https://jit.edu.in/
